---
- name: Controller Setup
  hosts: controller
  vars:
    playbook: controller-setup
    user: "apollo"
    home: "/home/apollo"
    suhome: "/root"
    ansdir: "{{ home }}/.ansible"
    bupdir: "{{ ansdir }}/bak/{{ playbook }}"
  tasks:
# Prep
    - name: Ansible Directories
      file:
        path: "{{ bupdir }}"
        state: directory
    - name: Backup Files
      shell: "cp -av {{ files | join(' ') }} {{ bupdir }}"
      vars:
        files:
        - /etc/chrony.conf
      args:
        creates: "{{ bupdir }}/chrony.conf"

# User Config
    - name: Update Passwords
      user:
        name: root
        password: "$6$rounds=656000$6E9Tq9lnQHnz.A06$g/7vFnchshxeYY0OdZMeZkLyKewv1O6HaIvpBj52zOtOjq9nXfiTAWgg/L8tg0e2ZZhNj8G7i8WCVigfaFXXm0"

# Networking
    - name: IPTables TCP
      iptables:
        chain: INPUT
        destination_port: "{{ item }}"
        protocol: tcp
        jump: ACCEPT
      loop:
        # HTTPd
        - 80
        # MySQL
        - 3306
        # RabbitMQ
        - 4369
        - 5671:5672
        - 25672
        # EtcD
        - 2379:2380
        # MemCacheD
        - 11211
    - name: IPTables UDP
      iptables:
        chain: INPUT
        destination_port: "{{ item }}"
        protocol: udp
        jump: ACCEPT
      loop:
        # NTP
        - 123
        # MemCacheD
        - 11211
    - name: Save IPTables
      shell: "service iptables save"

# Service Install/Config
    - name: Install Services
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        # SQL
        - mariadb
        - mariadb-server
        - python2-PyMySQL
        - MySQL-python
        # Message Queue
        - erlang
        - rabbitmq-server
        # Cache
        - memcached
        - python-memcached
        # Misc
        - etcd
    - name: Check yum versionlock
      shell: "grep erlang /etc/yum/pluginconf.d/versionlock.list"
      register: verslock
      ignore_errors: yes
    - name: Version Lock Packages
      shell: "yum versionlock {{ item }}"
      loop:
        - erlang*
      when: verslock.rc != 0

    # SQL
    - name: MariaDB config
      template:
        src: ../Templates/etc/my.cnf.d/openstack.cnf.j2
        dest: /etc/my.cnf.d/openstack.cnf
    - name: MariaDB Service
      service:
        name: mariadb
        state: restarted
        enabled: True
    - name: Remove MySQL Default User
      mysql_user:
        name: ""
        host_all: yes
        state: absent
    - name: Set MySQL root User Password
      mysql_user:
        name: 'root'
        host_all: yes
        password: controller
    - name: Upload .my.cnf
      template:
        src: ../Templates/etc/.my.cnf.j2
        dest: "{{ item }}/.my.cnf"
      loop:
        - "{{ home }}"
        - "{{ ansible_env.HOME }}"

    # NTP
    - name: Update chrony.conf
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^\s*#?\s*allow [0-9]+\..*'
        line: 'allow 192.168.124.0/24'
      register: chrony
    - name: Restart chrony
      service:
        name: chronyd
        state: restarted
      when: chrony.changed == True

    # Message Queue
    - name: Erlang User
      user:
        name: epmd
        system: yes
#    TESTING
#    https://bugzilla.redhat.com/show_bug.cgi?id=1104843
#    - name: Backup Files
#      shell: "cp -av {{ files | join(' ') }} {{ bupdir }}"
#      files:
#        - /usr/lib/systemd/system/epmd.socket
#        - /usr/lib/systemd/system/epmd@.socket
#      args:
#        creates: "{{ bupdir }}/epmd.socket"
#    - name: Update epmd.socket files
#      lineinfile:
#        path: "{{ item.path }}"
#        regexp: "{{ item.regexp }}"
#        line: "{{ item.line }}"
#      loop:
#        - { path: /usr/lib/systemd/system/epmd.socket,  regexp: "ListenStream=.*", line: "ListenStream=0.0.0.0:4369" }
#        - { path: /usr/lib/systemd/system/epmd@.socket
    - name: RabbitMQ Service
      service:
        name: rabbitmq-server
        state: started
        enabled: True
    - name: RabbitMQ User
      rabbitmq_user:
        user: openstack
        password: openstack
        permissions:
          - vhost: /
            configure_priv: .*
            write_priv: .*
            read_priv: .*
        state: present

    # Cache
    - name: Backup memcached Conf File
      shell: "cp -av /etc/sysconfig/memcached {{ bupdir }}"
      args:
        creates: "{{ bupdir }}/memcached"
    - name: Configure MemCacheD
      lineinfile:
        path: /etc/sysconfig/memcached
        regexp: '^OPTIONS=.*'
        line: 'OPTIONS=""'
      register: memcached
    - name: Restart MemCacheD
      service:
        name: memcached
        state: restarted
        enabled: True
      when: memcached.changed == True

    # Etcd
    - name: Set IP Address
      set_fact:
        ipaddr: "{{ ansible_default_ipv4.address }}"
    - name: Etcd Conf Dir
      file:
        name: "{{ home }}/.ansible/conf/etcd"
        state: directory
#    - name: Get Etcd Token
#      uri:
#        url: 'https://discovery.etcd.io/new?size=1'
#        creates: "{{ home }}/.ansible/conf/etcd/token"
#        dest: "{{ home }}/.ansible/conf/etcd/token"
#    - name: Set Etcd Token
#      shell: "cat {{ home }}/.ansible/conf/etcd/token"
#      register: etcdtoken
    - name: Backup etcd Conf File
      shell: "cp -av /etc/etcd/etcd.conf {{ bupdir }}"
      args:
        creates: "{{ bupdir }}/etcd.conf"
    - name:
      lineinfile:
        path: /etc/etcd/etcd.conf
        regexp: '^\s*#?\s*{{ item.opt }}=.*'
        line: '{{ item.opt }}="{{ item.val }}"'
      loop:
        - { opt: "ETCD_LISTEN_PEER_URLS", val: "http://{{ ipaddr }}:2380" }
        - { opt: "ETCD_LISTEN_CLIENT_URLS", val: "http://{{ ipaddr}}:2379,http://localhost:2379" }
        - { opt: "ETCD_NAME", val: "controller" } 
        - { opt: "ETCD_INITIAL_ADVERTISE_PEER_URLS", val: "http://{{ ipaddr }}:2380" }
        - { opt: "ETCD_ADVERTISE_CLIENT_URLS", val: "http://{{ ipaddr }}:2379" }
        - { opt: "ETCD_INITIAL_CLUSTER", val: "controller=http://{{ ipaddr }}:2380" }
        - { opt: "ETCD_INITIAL_CLUSTER_TOKEN", val: "etcd-cluster-01" }
        - { opt: "ETCD_INITIAL_CLUSTER_STATE", val: "new" }
        # Not needed
        # - { opt: "ETCD_DISCOVERY", val: "{{ etcdtoken.stdout }}" }
      register: etcd
    - name: Start Etcd Service
      service:
        name: etcd
        state: restarted
        enabled: True
      when: etcd.changed == True 

# Update Progress
    - name: Progress File
      file:
        path: "{{ ansdir }}/progress/{{ playbook }}"
        state: touch
