---
- hosts: controller
  vars:
    playbook: controller-setup
    user: "apollo"
    home: "/home/apollo"
    suhome: "/root"
    ansdir: "{{ home }}/.ansible"
    bupdir: "{{ ansdir }}/bak/{{ playbook }}"
  tasks:
# Backup Files
    - name: Backup Directory
      file:
        path: "{{ bupdir }}"
        state: directory
    - name: Backup Files
      shell: "cp -av {{ files | join(' ') }} {{ bupdir }}"
      vars:
        files:
        - /etc/chrony.conf
      args:
        creates: "{{ bupdir }}/chrony.conf"

# User Config
    - name: Update Passwords
      user:
        name: root
        password: "$6$rounds=656000$6E9Tq9lnQHnz.A06$g/7vFnchshxeYY0OdZMeZkLyKewv1O6HaIvpBj52zOtOjq9nXfiTAWgg/L8tg0e2ZZhNj8G7i8WCVigfaFXXm0"

# Networking
    - name: Update Hostname
      hostname:
        name: ctrl.centos.rdo
    - name: Firewall Services
      firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: True
        permanent: True
      loop:
        - ntp
        - mysql
    - name: Firewall Ports
      firewalld:
        port: "{{ item }}/tcp"
        state: enabled
        immediate: True
        permanent: True
      loop:
        - 4369
        - 5671-5672
        - 25672

# Service Install/Config
    - name: Install Services
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        # SQL
        - mariadb
        - mariadb-server
        - python2-PyMySQL
        # Message Queue
        - rabbitmq-server

    - name: MariaDB config
      template:
        src: ../Templates/etc/my.cnf.d/openstack.cnf.j2
        dest: /etc/my.cnf.d/openstack.cnf
    - name: MariaDB Service
      service:
        name: mariadb
        state: restarted
        enabled: True
# Still working this one out...
#    - name: MySQL Secure Installation
#      shell: "mysql_secure_installation"

    # NTP
    - name: Update chrony.conf
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^\s*#?\s*allow [0-9]+\..*'
        line: 'allow 192.168.124.0/24'
      register: chrony
    - name: Restart chrony
      service:
        name: chronyd
        state: restarted
      when: chrony.changed == True

    # Message Queue
    - name: RabbitMQ Service
      service:
        name: rabbitmq-server
        state: started
        enabled: True
    - name: RabbitMQ User
      rabbitmq_user:
        user: openstack
        password: openstack
        permissions:
          - vhost: /
            configure_priv: .*
            write_priv: .*
            read_priv: .*
        state: present
